In [1]:
# https://gist.github.com/NiharG15/cd8272c9639941cf8f481a7c4478d525



import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

iris_data = load_iris() # load the iris dataset

print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(iris_data.target[:5])

x = iris_data.data
y_ = iris_data.target.reshape(-1, 1) # Convert data to a single column

# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
#print(y)

# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

# Build the model

model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Using TensorFlow backend.
/Users/liampearson/opt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/liampearson/opt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:494: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/liampearson/opt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:495: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qi

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]
Neural Network Model Summary: 
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 10)                50        
_________________________________________________________________
fc2 (Dense)                  (None, 10)                110       
_________________________________________________________________
output (Dense)               (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/200
 - 0s - loss: 1.0117 - acc: 0.2000
Epoch 2/200
 - 0s - loss: 0.9334 - acc: 0.6500
Epoch 3/200
 - 0s - loss: 0.8812 - acc: 0.6750
Epoch 4/200
 - 0s - loss: 0.8456 - acc: 0.6833
Epoch 5/200
 - 0s - loss: 0.8160 - acc: 0.69

 - 0s - loss: 0.0647 - acc: 0.9833
Epoch 153/200
 - 0s - loss: 0.0604 - acc: 0.9833
Epoch 154/200
 - 0s - loss: 0.0628 - acc: 0.9833
Epoch 155/200
 - 0s - loss: 0.0606 - acc: 0.9833
Epoch 156/200
 - 0s - loss: 0.0598 - acc: 0.9833
Epoch 157/200
 - 0s - loss: 0.0617 - acc: 0.9833
Epoch 158/200
 - 0s - loss: 0.0600 - acc: 0.9833
Epoch 159/200
 - 0s - loss: 0.0577 - acc: 0.9833
Epoch 160/200
 - 0s - loss: 0.0584 - acc: 0.9833
Epoch 161/200
 - 0s - loss: 0.0632 - acc: 0.9833
Epoch 162/200
 - 0s - loss: 0.0584 - acc: 0.9833
Epoch 163/200
 - 0s - loss: 0.0582 - acc: 0.9917
Epoch 164/200
 - 0s - loss: 0.0585 - acc: 0.9833
Epoch 165/200
 - 0s - loss: 0.0661 - acc: 0.9667
Epoch 166/200
 - 0s - loss: 0.0573 - acc: 0.9833
Epoch 167/200
 - 0s - loss: 0.0559 - acc: 0.9833
Epoch 168/200
 - 0s - loss: 0.0556 - acc: 0.9833
Epoch 169/200
 - 0s - loss: 0.0569 - acc: 0.9833
Epoch 170/200
 - 0s - loss: 0.0554 - acc: 0.9833
Epoch 171/200
 - 0s - loss: 0.0590 - acc: 0.9917
Epoch 172/200
 - 0s - loss: 0.0550

In [2]:
model.save('model.h5')

In [6]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
print("sample input:",test_x[:1])
print("sample predcition:",model.predict(test_x[:1]))

In [76]:
print("sample input:",test_x[:1])
print("sample pumodel.predict(test_x[:1])
model.predict(np.asarray([[5. , 3.5, 1.3, 0.3]]))

sample input: [[5.  3.5 1.3 0.3]]
sample predcition: [[9.9930930e-01 6.9067377e-04 1.5728773e-16]]


array([[9.9930930e-01, 6.9067377e-04, 1.5728773e-16]], dtype=float32)

In [46]:
model.predict(test_x[:1])

#type(test_x[:2])

print(type(test_x[:1]))
type(test_x[:1][0])

a1 = np.array([1,2,3,4])
print(type(np.array(a1)))

model.predict(np.array(a1))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


ValueError: Error when checking input: expected fc1_input to have shape (4,) but got array with shape (1,)

In [4]:
# https://machinelearningmastery.com/save-load-keras-deep-learning-models/

# serialize model to JSON
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model_weights.h5")
print("Saved model to disk")

Saved model to disk


In [5]:
## LOAD MODEL
model_location = '/Users/liampearson/Google Drive/YouTube/5. Deploy keras .h5 to aws/models/model.h5'

# load a saved model
#import tensorflow
from keras.models import load_model

 
# load model
model = load_model(model_location)